version: "3.4"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5431:5432"
  api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    depends_on:
      - db
